services:
  next:
    image: ghcr.io/baptiste-boimard/cicd-cours-next:latest
    ports:
      - 3000:3000

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: next --interval 30