services:
  next:
    image: ghcr.io/baptiste-boimard/cicd-cours:main
    ports:
      - 8080:3000

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: next --interval 30