name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build

  test:
    # if: github.ref == 'refs/heads/main' 
    # permet de choisir une branche 
    runs-on: ubuntu-latest
    needs: build
    # strategy:
    #   matrix:
    #     browser: [chrome, edge]
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: npm run build
          start: npm run start
          browser: chrome
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
    
  build-and-push-image:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    # needs: [build, test]
    steps:
        - uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - run: | 
            ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "\
            ls -la && \
            cd cicd-cours && \
            git pull && \
            sudo docker compose -f docker-compose.yml -d up --pull=always"
            # le -d permet de se detacher du process et donc d'eviter qu'il start sur le ubuntu virtuel
            #    pm2 start .. ou pm2 restart all && \

  